server:
  port: 8085
spring:
  ai:
    mcp:
      server:
        name: person-mcp-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages

  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
logging.level.org.springframework.ai: DEBUG
logging.level.io.modelcontextprotocol.server: DEBUG
