server:
  port: 8086
logging.level.org.springframework.ai: DEBUG
spring:
  ai:
    mcp:
      client:
        type: SYNC
        sse:
          transport-mode : WEB
          connections:
            person-mcp-server:
              url: http://localhost:8085
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        enabled: true # By default, it's true, this triggers the autoconfiguration.
        options:
          model: gpt-4o
          temperature: 0.7
          max_completion_tokens: 2000
          internal-tool-execution-enabled: true
  autoconfigure:
#    exclude: org.springframework.ai.autoconfigure.mcp.client.SseHttpClientTransportAutoConfiguration
  main:
    banner-mode: off